#!/usr/bin/env python3

import importlib
import os
import os.path

from tests.util.test import TestFunctionType


def all_modules_in(pkg):
    return (
        path[:-3].replace("/", ".") for path in
        (
            os.path.join(root, f)
            for root, _, files in os.walk("tests")
            for f in files
        )
        if path.endswith(".py") and not path.endswith("__init__.py")
    )


def all_tests_in(mod):
    return (
        (mod.__name__ + "." + name, fn) for name, fn
        in mod.__dict__.items() if isinstance(fn, TestFunctionType)
    )


count = 0
for modpath in all_modules_in("tests"):
    mod = importlib.import_module(modpath)
    for (name, test) in all_tests_in(mod):
        print("  " + name)
        test()
        count += 1

if count == 0:
    raise AssertionError("No tests were found!")

print("All %d tests passed." % count)
